/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sample_zhanganl_ndkjnidemo3_NdkJniUtils */

#ifndef _Included_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils
#define _Included_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sample_zhanganl_ndkjnidemo3_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject,jstring);

JNIEXPORT jint JNICALL Java_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils_sum
        (JNIEnv *, jobject,jintArray);

JNIEXPORT jobjectArray JNICALL Java_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils_initInt2DArray
        (JNIEnv *env, jclass cls, int size);
JNIEXPORT void JNICALL Java_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils_accessField
        (JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils_accessStaticField
        (JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils_nativeMethod
        (JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils_accessConstructMethod
        (JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_com_sample_zhanganl_ndkjnidemo3_NdkJniUtils_accessParentMethod
        (JNIEnv *env, jobject obj);
#ifdef __cplusplus
}
#endif
#endif
